// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKS_intern_server.Data;

#nullable disable

namespace TKS_intern_server.Migrations
{
    [DbContext(typeof(TKS_internContext))]
    [Migration("20250714093146_Add-table-phieu-nhap-kho-and-chi-tiet")]
    partial class Addtablephieunhapkhoandchitiet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Don_Gia_Nhap");

                    b.Property<int>("PhieuNhapKhoId")
                        .HasColumnType("int")
                        .HasColumnName("Nhap_Kho_ID");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("San_Pham_ID");

                    b.Property<decimal>("SoLuongNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SL_Nhap");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapKhoId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("tbl_DM_Nhap_Kho_Raw_Data", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Don_Vi_Tinh");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TenDonViTinh")
                        .IsUnique();

                    b.ToTable("tbl_DM_Don_Vi_Tinh", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Kho");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TenKho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Kho", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.KhoUser", b =>
                {
                    b.Property<string>("MaDangNhap")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Ma_Dang_Nhap");

                    b.Property<int>("KhoId")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("MaDangNhap", "KhoId");

                    b.HasIndex("KhoId");

                    b.ToTable("tbl_DM_Kho_User", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("MaLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ma_Loai_San_Pham");

                    b.Property<string>("TenLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Loai_San_Pham");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MaLoaiSanPham")
                        .IsUnique();

                    b.HasIndex("TenLoaiSanPham")
                        .IsUnique();

                    b.ToTable("tbl_DM_Loai_San_Pham", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ma_NCC");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_NCC");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MaNhaCungCap")
                        .IsUnique();

                    b.HasIndex("TenNhaCungCap")
                        .IsUnique();

                    b.ToTable("tbl_DM_Nha_Cung_Cap", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int>("KhoId")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("NgayNhapKho")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ngay_Nhap_Kho");

                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("int")
                        .HasColumnName("NCC_ID");

                    b.Property<string>("SoPhieuNhapKho")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("So_Phieu_Nhap_Kho");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("KhoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoPhieuNhapKho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Phieu_Nhap_Kho", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DonViTinhId")
                        .HasColumnType("int")
                        .HasColumnName("Don_Vi_Tinh_ID");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int>("LoaiSanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("Loai_San_Pham_ID");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ma_San_Pham");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_San_Pham");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.ToTable("tbl_DM_San_Pham", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("PhieuNhapKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.KhoUser", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.SanPham", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhapKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
