// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKS_intern_server.Data;

#nullable disable

namespace TKS_intern_server.Migrations
{
    [DbContext(typeof(TKS_internContext))]
    [Migration("20250721045638_Change-foreign-key-to-nulable2")]
    partial class Changeforeignkeytonulable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DonGiaNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Don_Gia_Nhap");

                    b.Property<int>("PhieuNhapKhoId")
                        .HasColumnType("int")
                        .HasColumnName("Nhap_Kho_ID");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("San_Pham_ID");

                    b.Property<decimal>("SoLuongNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SL_Nhap");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapKhoId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("tbl_DM_Nhap_Kho_Raw_Data", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuXuatKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DonGiaXuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Don_Gia_Xuat");

                    b.Property<int>("PhieuXuatKhoId")
                        .HasColumnType("int")
                        .HasColumnName("Xuat_Kho_ID");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("San_Pham_ID");

                    b.Property<int>("SoLuongXuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("int")
                        .HasColumnName("SL_Xuat");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PhieuXuatKhoId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("tbl_DM_Xuat_Kho_Raw_Data", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Don_Vi_Tinh");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TenDonViTinh")
                        .IsUnique();

                    b.ToTable("tbl_DM_Don_Vi_Tinh", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Kho");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TenKho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Kho", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.KhoUser", b =>
                {
                    b.Property<string>("MaDangNhap")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Ma_Dang_Nhap");

                    b.Property<int>("KhoId")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MaDangNhap", "KhoId");

                    b.HasIndex("KhoId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_DM_Kho_User", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("MaLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ma_Loai_San_Pham");

                    b.Property<string>("TenLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Loai_San_Pham");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MaLoaiSanPham")
                        .IsUnique();

                    b.HasIndex("TenLoaiSanPham")
                        .IsUnique();

                    b.ToTable("tbl_DM_Loai_San_Pham", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ma_NCC");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_NCC");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MaNhaCungCap")
                        .IsUnique();

                    b.HasIndex("TenNhaCungCap")
                        .IsUnique();

                    b.ToTable("tbl_DM_Nha_Cung_Cap", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int?>("KhoId")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("NgayNhapKho")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ngay_Nhap_Kho");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int")
                        .HasColumnName("NCC_ID");

                    b.Property<string>("SoPhieuNhapKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("So_Phieu_Nhap_Kho");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("KhoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoPhieuNhapKho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Phieu_Nhap_Kho", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuXuatKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int?>("KhoId")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("NgayXuatKho")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ngay_Xuat_Kho");

                    b.Property<string>("SoPhieuXuatKho")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("So_Phieu_Xuat_Kho");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("KhoId");

                    b.HasIndex("SoPhieuXuatKho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Phieu_Xuat_Kho", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DonViTinhId")
                        .HasColumnType("int")
                        .HasColumnName("Don_Vi_Tinh_ID");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int?>("LoaiSanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("Loai_San_Pham_ID");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ma_San_Pham");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_San_Pham");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.ToTable("tbl_DM_San_Pham", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("PhieuNhapKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.ChiTietPhieuXuatKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.PhieuXuatKho", "PhieuXuatKho")
                        .WithMany("ChiTietPhieuXuatKhos")
                        .HasForeignKey("PhieuXuatKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuXuatKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.KhoUser", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKS_intern_shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TKS_intern_shared.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuXuatKho", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.SanPham", b =>
                {
                    b.HasOne("TKS_intern_shared.Models.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TKS_intern_shared.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhapKhos");
                });

            modelBuilder.Entity("TKS_intern_shared.Models.PhieuXuatKho", b =>
                {
                    b.Navigation("ChiTietPhieuXuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
